### Variables
@baseUrl = http://127.0.0.1:8000
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NjIwMDgzLCJpYXQiOjE3NTc2MTY0ODMsImp0aSI6IjljZTYyZjU2Y2Y1ZDQ5OTZiOWUyZWEyNjNlNThiMDliIiwidXNlcl9pZCI6MX0.6fjshP9LFuVCG837-BC1iHwuPQIw5Z8IFIBOcfUnE0Q"


### Get JWT Token
POST {{baseUrl}}/accounts/token/
Content-Type: application/json

{
    "username": "testuser2",
    "password": "test2pass123"
}

### Refresh Token
POST {{baseUrl}}/accounts/token-refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODIyMTg0OSwiaWF0IjoxNzU3NjE3MDQ5LCJqdGkiOiI0NGI0YWFhMmFhODc0NjMwOTI2MjQ3ZTdhZTlmZGIzNiIsInVzZXJfaWQiOjN9.TpynhWTJCZar6BqrdHB5MXN_B2F89R-IhDE49C6KrlQ"
}

### Verify Token
POST {{baseUrl}}/accounts/token-verify/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NjIwNjY5LCJpYXQiOjE3NTc2MTcwNDksImp0aSI6Ijk4NzkyYjFiODhiZjQ5YzBhOTM3YmYzYzJlYTA2MWIzIiwidXNlcl9pZCI6M30.7AHv9PMtcqs5nRUykCao6gl19eNgWwoBSa15gm0Pu5A"
}

### Test Account Endpoints (replace with your actual endpoints)
GET {{baseUrl}}/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NjIwMTkyLCJpYXQiOjE3NTc2MTY0ODMsImp0aSI6IjJiOWMyN2ZkMTJmZDQzYjdhMzJmNDA3N2QwZDg5ZGIwIiwidXNlcl9pZCI6MX0.sDd3tg7N-0Cr4WmL82WsEsay7HiIALjovsGDjWZ3TrY

### Create Account (example)
POST {{baseUrl}}/accounts/
Content-Type: application/json

{
    "username": "testuser2",
    "email": "test2@example.com",
    "password": "test2pass123"
}

### test get a user
PUT {{baseUrl}}/accounts/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3ODc3MjkyLCJpYXQiOjE3NTc4NzM2OTIsImp0aSI6IjIwYmNlYjU3YTAyZjQ3ZTQ4NDk0MWFmNzdkNDliMjIzIiwidXNlcl9pZCI6M30.QOD0zLR6zaMpG7_tWu7ABrvbyTh3C0xRf-JMK4teZ3c

{
    "first_name": "first name test",
    "last_name": "last name test"
}

### test rest password
GET {{baseUrl}}/accounts/password-reset/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3NjIwMDgzLCJpYXQiOjE3NTc2MTY0ODMsImp0aSI6IjljZTYyZjU2Y2Y1ZDQ5OTZiOWUyZWEyNjNlNThiMDliIiwidXNlcl9pZCI6MX0.6fjshP9LFuVCG837-BC1iHwuPQIw5Z8IFIBOcfUnE0Q

### test /me endpoint
GET {{baseUrl}}/accounts/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3ODc1Nzg3LCJpYXQiOjE3NTc4NzIxODcsImp0aSI6IjM1NGI4OGRjZWI1MjRlMjE5ZmRiNjVhYWQ0ZTMyN2VlIiwidXNlcl9pZCI6M30.Txl55n3s6mBkv63m7z_C5K9VkUH8SopuDbT-AQuwWVM

### delte a user
DELETE {{baseUrl}}/accounts/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3ODc1Nzg3LCJpYXQiOjE3NTc4NzIxODcsImp0aSI6IjM1NGI4OGRjZWI1MjRlMjE5ZmRiNjVhYWQ0ZTMyN2VlIiwidXNlcl9pZCI6M30.Txl55n3s6mBkv63m7z_C5K9VkUH8SopuDbT-AQuwWVM

